# Site settings
title: "Astral-99"
bye_message: "Thx!"
baseurl: "/"
url: "https://astral.github.io"
disqus: astral99

# Header settings
nick: "astral99"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "astral99"
blog:
    server: ""
    nick: ""
fingerprint_key: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
